# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: octopusdeploy.octopus-deploy-build-release-tasks.octo-installer.OctoInstaller@7
  displayName: 'Install Octopus CLI tool version '
  inputs:
    octopusVersion: 2.21.3

- pwsh: |
      $cliargs = @(
        "--project", "RunbookADOTest",
        "--name", "Runbook",
        "--environment", "Dev",
        "--git-ref", "refs/heads/main",
        "--package-version", "1.0.3",
        "--server", "${env:OCTOPUSSERVERURL}",
        "--api-key", "${env:OCTOPUSAPIKEY}",
        "--space", "Default"
        "--no-prompt"
      )
      $output = & octopus runbook run @cliArgs 2>&1
      $output | ForEach-Object { Write-Host $_ }
      Write-Host "Exit code: $LASTEXITCODE"
      if ($LASTEXITCODE -ne 0) {
        throw "Octopus runbook run failed with exit code $LASTEXITCODE"
      }
      displayName: 'Run Octopus Runbook (CaC project) with pinned package version'